// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/links": {
    params: {};
  };
  "/hasqtan": {
    params: {};
  };
  "/my-work-on-links": {
    params: {};
  };
  "/writing": {
    params: {};
  };
  "/writing/chinese-restaurant": {
    params: {};
  };
  "/writing/the-final-fumes-of-the-rutgers-teachers-strike": {
    params: {};
  };
  "/writing/some-poems": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/links" | "/hasqtan" | "/my-work-on-links" | "/writing" | "/writing/chinese-restaurant" | "/writing/the-final-fumes-of-the-rutgers-teachers-strike" | "/writing/some-poems";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/links.tsx": {
    id: "routes/links";
    page: "/links";
  };
  "routes/hasqtan.tsx": {
    id: "routes/hasqtan";
    page: "/hasqtan";
  };
  "routes/my-work-on-links.tsx": {
    id: "routes/my-work-on-links";
    page: "/my-work-on-links";
  };
  "./routes/writing/home.tsx": {
    id: "routes/writing/home";
    page: "/writing";
  };
  "./routes/writing/chinese-restaurant.tsx": {
    id: "routes/writing/chinese-restaurant";
    page: "/writing/chinese-restaurant";
  };
  "./routes/writing/the-final-fumes-of-the-rutgers-teachers-strike.tsx": {
    id: "routes/writing/the-final-fumes-of-the-rutgers-teachers-strike";
    page: "/writing/the-final-fumes-of-the-rutgers-teachers-strike";
  };
  "./routes/writing/some-poems.tsx": {
    id: "routes/writing/some-poems";
    page: "/writing/some-poems";
  };
};